spring.application.name=chat-app-server-kotlin

server.port=8080

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jwt.secret=${SPRING_JWT_SECRET}
google.web.client-id=${GOOGLE_WEB_CLIENT_ID}
